#ElFinder
fm_elfinder:
    #assets_path: / # default is /assets, this is where css/js elfinder files are
    instances:
        default:
            locale: "en" # defaults to current request locale
            # editor: custom # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
            editor_template: base.html.twig
            #path_prefix: / # for setting custom assets path prefix, useful for non vhost configurations, i.e. http://127.0.0.1/mysite/
            #fullscreen: true|false # default is true, applies to simple and ckeditor editors
            #theme: smoothness # jquery theme, default is 'smoothness'
            relative_path: false
            visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg'] # only show these mime types, defaults to show all
            connector:
                #debug: true|false # defaults to false
                roots:       # at least one root must be defined, defines root filemanager directories
                    aws_s3:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: Flysystem
                        url: 'http://%env(AWS_BUCKET_NAME)%.s3.%env(AWS_REGION)%.amazonaws.com'
                        tmb_url: "/uploads/.tmb"
                        tmb_path: "uploads/.tmb"
                        tmb_size: 200
                        flysystem:
                            type: aws_s3_v3
                            options:
                                aws_s3_v3:
                                    key: "%env(AWS_ACCESS_KEY)%"
                                    secret: "%env(AWS_SECRET_ACCESS_KEY)%"
                                    region: "%env(AWS_REGION)%"
                                    bucket_name: "%env(AWS_BUCKET_NAME)%"
                                    version: latest
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        disabled_commands: ['cut', 'mkfile', 'copy']