imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    security_encoder_cost: 12

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "/tmp"
    fragments:       ~
    http_method_override: true
    assets: ~

#Assetic
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

#ElFinder
fm_elfinder:
    #assets_path: / # default is /assets, this is where css/js elfinder files are
    instances:
        default:
            locale: "%locale%" # defaults to current request locale
            editor: custom # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
            editor_template: AppBundle:default:index.html.twig
            #path_prefix: / # for setting custom assets path prefix, useful for non vhost configurations, i.e. http://127.0.0.1/mysite/
            #fullscreen: true|false # default is true, applies to simple and ckeditor editors
            #theme: smoothness # jquery theme, default is 'smoothness'
            include_assets: false # disable if you want to manage loading of javascript and css assets manually
            relative_path: false
            visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg'] # only show these mime types, defaults to show all
            connector:
                #debug: true|false # defaults to false
                roots:       # at least one root must be defined, defines root filemanager directories
                    uploads:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: Flysystem
                        url: "https://s3.%aws_region%.amazonaws.com/%aws_bucket_name%/"
                        tmb_url: "/uploads/.tmb"
                        tmb_path: "uploads/.tmb"
                        tmb_size: 200
                        flysystem:
                            type: aws_s3_v3
                            options:
                                aws_s3_v3:
                                    key: "%aws_access_key%"
                                    secret: "%aws_secret_access_key%"
                                    region: "%aws_region%"
                                    bucket_name: "%aws_bucket_name%"
                                    version: latest
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        disabled_commands: ['cut', 'mkfile', 'copy']