login:
    path: /login
    defaults:  { _controller: "AppBundle:Default:login" }

logout:
   path: /logout

#ElFinder routing
ef_connect:
    path:  /efconnect/{instance}/{homeFolder}
    defaults: { _controller: FMElfinderBundle:ElFinder:load, instance: default, homeFolder: '' }

homepage:
    path: /{instance}/{homeFolder}
    defaults: { _controller: FMElfinderBundle:ElFinder:show, instance: default, homeFolder: '' }

