# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: "%security_encoder_cost%"
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$SUn7dQtxPjwBLw2K/.Y2O.ygW1IRPdgEyd7Eq3/SCdEKll70L1KWO
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
           pattern: ^/(_(profiler|wdt)|css|images|js)/
           security: false

        secured_area:
           anonymous: ~
           form_login:
               login_path: login
               check_path: login
           logout:
               path: /logout
               target: /
           guard:
               authenticators:
                 - app.form_authenticator
    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, role: ROLE_ADMIN }
